OS_IGNORED_COLUMNS=["ID", "NAMES_URI", "NAME1_LANG", "NAME2_LANG", "MOST_DETAIL_VIEW_RES",
                "LEAST_DETAIL_VIEW_RES", "MBR_XMIN", "MBR_YMIN", "MBR_XMAX", "MBR_YMAX", "POSTCODE_DISTRICT", 
                "POSTCODE_DISTRICT_URI", "POPULATED_PLACE_URI", "DISTRICT_BOROUGH_URI", "DISTRICT_BOROUGH_TYPE", 
                "COUNTY_UNITARY_URI", "COUNTY_UNITARY_TYPE", "REGION_URI", "COUNTRY_URI", "RELATED_SPATIAL_OBJECT", "SAME_AS_DBPEDIA"]

ONS_IGNORED_COLUMNS=["TOWN_2011CODE", "Population Growth 2001-2019 (%)"]